### ISSUE TITLE
Syntax Error on Line 207

### ISSUE THREAD

**Issue by c1p81** [rokubun/android_rinex#1]
Good Morning
i have a Syntax Error on Line 207 
def print(self)

i use a Centos 7
Thanks for the reply
Luca

**Comment by c1p81** [comment]
Ok i have found the solution
the script is for Python 3.x but Centos have Python 2.x

everything works fine in Python 3.x
Thanks

**Comment by alexlopezc** [comment]
Thanks for the feedback
