### ISSUE TITLE
When Glonass svid defaults to FCN instead of OSN the program halts

### ISSUE THREAD

**Issue by anumerico** [rokubun/android_rinex#7]
Hello, I am converting android GNSS raw logs to RINEX for RTK postprocessing.
The problem is when the program finds a svid > 50, in the Glonass defaulting to FCN case, it says it skips that satellite but really what happens is that the program halts and doesn't output any RINEX at all instead of resuming its course until outputting the RINEX file.
The answer might be in some of the command gnsslogger_to_rnx options but there is no documentation about  those options.
Any help appreciated thanks.
![Screenshot from 2020-05-07 10-46-09 (1)](https://user-images.githubusercontent.com/54191578/81274472-9fbd7b00-9050-11ea-957c-5ac4905cbac8.png)

**Comment by mgfernan** [comment]
Hi, @anumerico , can you share a sample file we could try?

In the meantime, you could try our online service (https://jason.rokubun.cat) to convert the data to RINEX or even process it with PPK. You just need to register.

Best
Miquel

**Comment by anumerico** [comment]
Yes @Tryskele , that file for example.
I want to use the tool as part of a pipeline.
At the moment im looking at the filter-mode to see if i can filter out those "bad" svids.
Btw thanks for your prompt reply.
P.s.:I'm running Ubuntu 19.10.

[gnss_log_2020_04_25_20_24_34.txt](https://github.com/rokubun/android_rinex/files/4591939/gnss_log_2020_04_25_20_24_34.txt)

**Comment by anumerico** [comment]
@Tryskele Are you doing any preprocessing of the raw file in your servers before feeding it to gnsslogger_to_rnx ?

**Comment by mgfernan** [comment]
No, we just feed that file in our converter as-is to generate the Rinex. Are you asking for any particular reason?

**Comment by anumerico** [comment]
Right now I'm thinking of 3 options:
a)Preprocess the file.
b)Find the right flag on the command line tool to filter those "bad" svids.
c)Find the bug in the software that makes the program halt.
Also I see I'm not the first one to encounter that issue:https://github.com/rokubun/android_rinex/issues/6
So I'm guessing its been sorted somehow before.
Just asking because if it works for you and not fore me, it be good to know what makes the difference.

**Comment by mgfernan** [comment]
Ah ok, we need to add a patch to the tool (which we will try to do in the following days). The converter tool used in the online service uses a different package (which is written in C), hence the difference. Ideally we'd like to use the same libraries but then we would need to add a dependency to the package, which we are a little reluctant to do...

**Comment by anumerico** [comment]
Thanks, that would be really helpful. :)

**Comment by anumerico** [comment]
Ok. So far i have managed to postprocess my gnsslogger file with the RINEX produced by your servers and comparing it to a reference geodesic vertex where the logs where taken the precision is good enough.. Now I'd like to do it producing the rinex file with the android_rinex tool, so far looking at awk, at the filter option (Could you explain a bit what is the sync filter option for?) and/or modfiying a bit your code..

**Comment by anumerico** [comment]
That fork solves the issue:
https://github.com/dmiralles2009/android-rinex
Thanks.

**Comment by Nronaldo** [comment]
I also encounter this question although I use the example data.

**Comment by alexlopezc** [comment]
Hi,

This issue has been fixed in commit [e3051892a3902ad9e7753cd679dad986ce1e081f](https://github.com/rokubun/android_rinex/commit/e3051892a3902ad9e7753cd679dad986ce1e081f)

Thank for using the tool

**Comment by anumerico** [comment]
I solved it using the @dmiralles2009 branch, got to say that @alexlopezc is a nice and elegant solution for that issue, also and what's weirding me out is that now commit https://github.com/rokubun/android_rinex/tree/cf7d9ce25833a1b51c9eb65d54c537a3fdb88f1c is working with the same test example i uploaded, so must have been something on the ubuntu 20.04 side and its libraries, or something related to python2 python3:
https://linuxize.com/post/python-range/
Also wondering, why are last @dmiralles2009 changes not being commited to the main branch?
