### ISSUE TITLE
ValueError: -- WARNING: Skipping measurement for GLONASS sat without OSN [ R106 ]

### ISSUE THREAD

**Issue by Nronaldo** [rokubun/android_rinex#8]
Hello
I want to use this tool to convert data from GNSSLOgger. However I encounter same questions with #7 #6  
The Tool gives warnings  Skipping measurement for GLONASS sat without OSN and doesnt output rinex file even when I use the example data provided by you. 
I test this tool on Windows 10 and input command in powershell. My command is :
 .\gnsslogger_to_rnx.bat -o nex.17o .\data\2.txt
Could you please give me some help?

**Comment by LorenzoStucchi** [comment]
Hi, I had the same issue some times ago and I partially solved it not considering these GLONASS satellites and giving them a fake name `RER`.

I explained it [here](https://github.com/LorenzoStucchi/RINEX_quality_analysis/tree/master/GNSSlogger2rinex).

**Comment by alexlopezc** [comment]
This issue has been fixed in commit [e3051892a3902ad9e7753cd679dad986ce1e081f](https://github.com/rokubun/android_rinex/commit/e3051892a3902ad9e7753cd679dad986ce1e081f)

Thank for using the tool
